<a href="https://colab.research.google.com/github/Megala30/Python-Workspace/blob/main/instacart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
mf = pd.read_csv('/content/order_products__train.csv')

In [5]:
mf.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [6]:
mf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

In [7]:
mf.shape

(1384617, 4)

In [8]:
order_count = mf['order_id'].value_counts()
display(order_count)

order_id
2813632    80
1395075    80
949182     77
2869702    76
341238     76
           ..
1231029     1
1230813     1
2473878     1
3420798     1
1932460     1
Name: count, Length: 131209, dtype: int64

In [11]:
mf.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [13]:
mf.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [14]:
mf.columns

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='object')

In [15]:
colmn_list = mf[['order_id', 'product_id', 'reordered']]
colmn_list

         order_id  product_id  reordered
0               1       49302          1
1               1       11109          1
2               1       10246          0
3               1       49683          0
4               1       43633          1
...           ...         ...        ...
1384612   3421063       14233          1
1384613   3421063       35548          1
1384614   3421070       35951          1
1384615   3421070       16953          1
1384616   3421070        4724          1

[1384617 rows x 3 columns]

In [17]:
print(mf.iloc[100 :121])

     order_id  product_id  add_to_cart_order  reordered
100       170       34582                  9          0
101       170       49593                 10          0
102       170       15093                 11          0
103       170       43841                 12          0
104       170       21137                 13          0
105       170       40354                 14          1
106       170       17794                 15          0
107       170       11182                 16          0
108       170       39190                 17          0
109       218        1194                  1          1
110       218        5578                  2          1
111       218       38159                  3          0
112       218       10305                  4          0
113       218       38557                  5          0
114       226       28199                  1          0
115       226       24852                  2          0
116       226       29883                  3          1
117       226       28427                  4          1
118       226        7754                  5          1
119       226       39947                  6          1
120       226       47307                  7          0

In [18]:
colmn_list = mf[['reordered']]
print(colmn_list > 1)

         reordered
0            False
1            False
2            False
3            False
4            False
...            ...
1384612      False
1384613      False
1384614      False
1384615      False
1384616      False

[1384617 rows x 1 columns]